import Router from "next/router";
import useLocalStorage from "@/customHooks/useLocalStorage";
import MainLayout from "@/components/Layout/MainLayout";
import Head from "next/head";
import {IProduct} from "@/components/Cards/Cards-types";
import ButtonInCart from "@/components/ButtonInCart/ButtonInCart";
import FavoritesProduct from "@/components/FavoritesProducts/FavoritesProduct";
import classes from "@/styles/shopping-cart.module.scss";
import Footer from "@/components/Footer/Footer";
import FooterBottom from "@/components/FooterBottom/FooterBottom";

export default function Favorites() {
    const [favoriteProducts] = useLocalStorage("favorites", []);
    const [cartItems] = useLocalStorage("products", []);
    const [numberOfFavorites] = useLocalStorage("favoritesNumber", 0);
    const goLinkHome = () => {
        Router.push('/')
    }
    return (
        <div className={classes.wrapper}>
            <MainLayout cartItems={cartItems} numberOfFavorites={numberOfFavorites}>
                <Head>
                    <title>Online store</title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <link rel="icon" href="/online-store.ico" />
                    <link
                        href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap"
                        rel="stylesheet" />

                </Head>
                <h1>Favorites</h1>
                <ButtonInCart onClick={goLinkHome}>Back home</ButtonInCart>
                {favoriteProducts?.length === 0 ? (
                    <h1 className={classes.no_items}> Нет товаров в избранном</h1>
                ) : (
                    <div className={classes.carts_container}>
                        {favoriteProducts?.map((item: IProduct) => (
                            <FavoritesProduct
                                key={item.id}
                                favoriteProduct={item}
                            />
                        ))}
                    </div>
                )}
            </MainLayout>
            {cartItems?.length > 0 ? (
                <Footer />
            ) : (
                <FooterBottom />
            )}
        </div>
    )
}